### ISSUE TITLE
ABCD and NIH (nihtbx_picvocab_uncorrected) Data

### ISSUE THREAD

**Issue by marafathussain** [Wayfear/BrainNetworkTransformer#5]
Hi there,

I must say, you did an impressive research work. I was wondering if you could share the .npy and .txt data for ABCD (which you mentioned in ABCD.yml file) and the NIH toolbox data as well. This would be a great help. I am trying to run your code and I have a very short time to do so. Your prepared data would save a lot of time for me.

Thanks a lot. Eagerly waiting to hear from you.

**Comment by Wayfear** [comment]
Thank you for your appreciation for this work!
Unfortunately, I cannot directly share the npy file with you due to NIMH policy. You will need to apply for access from NIMH. Besides, the preprocessing was done by Professor [Joshua Lukemire](https://sph.emory.edu/faculty/profile/index.php?FID=joshua-lukemire-12811). You may contact him to inquire about the process code and whether he can share it with you. But I can provide the used sample list in my study. Hope it is helpful.
